name: CI

on:
  pull_request:
    branches: [prd, stg, dev]
    types: [opened, reopened, synchronize, edited]
    paths-ignore: # Pushes that include only these changed files won't trigger actions
      - "**/README.md"
      - "**/.gitignore"
      - "**/doc/*"

jobs:
  env:
    name: Set Env Vars
    runs-on: ubuntu-latest
    steps:
      - name: Set up PRD Environment Variables
        if: ${{ github.base_ref == 'prd' }}
        run: |
          matrix='{
            "env":[
              {
                "aws_key_name":"byu_dept_fhtl_prd_key",
                "aws_secret_name":"byu_dept_fhtl_prd_secret"
              }
            ]
          }'
          echo matrix=`echo $matrix | jq -c .` >> $GITHUB_ENV

      - name: Set up STG Environment Variables
        if: ${{ github.base_ref == 'stg' || github.base_ref == 'dev' }}
        run: |
          matrix='{
            "env":[
              {
                "aws_key_name":"byu_dept_fhtl_dev_key",
                "aws_secret_name":"byu_dept_fhtl_dev_secret"
              }
            ]
          }'
          echo matrix=`echo $matrix | jq -c .` >> $GITHUB_ENV

    outputs:
      matrix: ${{ env.matrix }}
    
  auto-test:
    name: Run Automated Tests
    runs-on: ubuntu-latest
    needs: [env]
    strategy:
      matrix: ${{ fromJson(needs.env.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: |
            models
            presenters
            views
            tests
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets[matrix.env.aws_key_name] }}
          aws-secret-access-key: ${{ secrets[matrix.env.aws_secret_name] }}
          aws-region: us-west-2
      
      - name: Install PyFS
        run: pip install 'git+https://${{ secrets.RLL_BOT_PERSONAL_ACCESS_TOKEN }}@github.com/byuawsfhtl/PyFS.git@prd'

      - name: Install Boto4GS
        run: pip install "git+https://${{ secrets.RLL_BOT_PERSONAL_ACCESS_TOKEN }}@github.com/byuawsfhtl/Boto4GS.git@${{ github.ref }}"

      - name: Run Automated Tests
        run: |
          python tests/main.py
