name: CI

on:
  pull_request:
    branches: [prd, stg, dev]
    types: [opened, reopened, synchronize, edited]
    paths-ignore: # Pushes that include only these changed files won't trigger actions
      - "**/README.md"
      - "**/.gitignore"
      - "**/docs/*"

jobs:
  checkMeds:
    name: Check Meds (merge every day)
    runs-on: ubuntu-latest
    steps:
        - name: Check Meds
          uses: byuawsfhtl/MedsAction@v1.0.0
